### PR TITLE
Master update

### PR DESCRIPTION
**Pull request by jon-chuang**

### CODE REVIEW

**Comment by jon-chuang** [comment]
@kobigurk Can we get this merged pronto?

**Comment by kobigurk** [comment]
@jon-chuang sure. Next time be sure to tag me or ask for review so I notice :)
I'd merge it, but something is blocking - why is it 2 commits above scipr-lab master?

**Comment by jon-chuang** [comment]
Might be because of the yml changes + merge conflicts.

**Comment by kobigurk** [comment]
Oh I see.

Can we maybe align with Zexe master for this PR?

**Comment by jon-chuang** [comment]
Not sure how to do that.

**Comment by kobigurk** [comment]
Make this one completely reset just to Zexe master, it shouldn't be more than that.
Then in the next PR (the tests + refactor) add the extra commit we already have on our master.

**Comment by kobigurk** [comment]
@jon-chuang can you make the change?

**Comment by jon-chuang** [comment]
It's very confusing to me

**Comment by jon-chuang** [comment]
To do that, I think we can't do a merge, we must push --force directly to celo-org/zexe/master

**Comment by jon-chuang** [comment]
tbh I don't really think it matters

**Comment by kobigurk** [comment]
It matters because we want to start from a clean slate.

**Pull request merged**
